[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/wiki"
  to = "/wiki.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200
